version: '3.7'

services:
  localstack-dynamo:
    image: localstack/localstack:latest
    container_name: localstack-dynamo
    ports:
      - '4569:4569'
    environment:
      - SERVICES=dynamodb
      - DEBUG=1
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
volumes:
  db_data:

networks:
  example:
    driver: bridge